spring.application.name=backend

spring.profiles.active=dev
spring.jpa.open-in-view=true

server.tomcat.uri-encoding=UTF-8

server.error.include-stacktrace=never

######################## Swagger ###########################################
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=true