spring.application.name=backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=desafio_mazzatech_dev;encrypt=true;trustServerCertificate=true
spring.datasource.username=app_user
spring.datasource.password=App@Pass123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Carregamento do data.sql
spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data/data.sql

server.port=8181