spring.application.name=backend

spring.profiles.active=dev
spring.jpa.open-in-view=true

server.tomcat.uri-encoding=UTF-8

server.error.include-stacktrace=never

######################## Swagger ###########################################
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs
springdoc.cache.disabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.url=/openapi/openapi-editado.json